platform :ios,'7.0'
target ‘RuntimeDemo’ do

pod 'AFNetworking', '~> 2.6'
pod 'MJExtension', '~> 3.0.13'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDWebImage', '~> 3.8.2'
pod 'DACircularProgress', '~> 2.3.1'
pod 'pop', '~> 1.0.9'
pod 'POP+MCAnimate', '~> 2.0.1'
pod 'Masonry', '~> 1.0.2'

end